import { build } from "esbuild";
import { mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const directory = fileURLToPath(
  new URL("../apps/web/public/worklets/", import.meta.url),
);
await mkdir(directory, { recursive: true });
await build({
  absWorkingDir: root,
  entryPoints: ["packages/editor/playback.worklet.ts"],
  outfile: "apps/web/public/worklets/editor-pcm.js",
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "none",
  banner: {
    js: "/* Generated by scripts/build-editor-assets.ts from the tested local playback transport. */",
  },
});
